blank_issues_enabled: false
contact_links:
  - name: Problem with old world content
    url:  https://github.com/BigWigsMods?q=bigwigs-old-expansion-bosses&type=&language=
    about: Do NOT report issues with old world/expansion content here, report it on the appropriate expansion's GitHub page.
  - name: Question
    url:  https://discord.gg/jGveg85
    about: Please ask questions on our Discord!
