name: Package addon

on:
  push:
    branches:
      - master
      - classic
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags') == true || contains(github.event.head_commit.message, 'skip ci') != true

    steps:
      - name: Checkout addon
        uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Install luarocks
        run: |
          sudo apt-get -q install luarocks
          sudo luarocks install luacheck
          sudo luarocks install lanes

      - name: Run luacheck
        run: luacheck . -q

      - name: Update option files
        if: always()
        run: lua gen_option_values.lua

      - name: Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
